openapi: 3.0.1
info:
  title: Zitadel  OIDC
  description: >
    This API specification outlines the endpoints and operations for the Authorization Service. 
    It enables users to handle roles, role-permission mappings, role-group mappings, and process authorization requests.
  version: 0.1.0
servers:
- url: "{server}:{port}/"
  description: >
    The base URL for the API. Use this as the starting point for making API requests.
  variables:
    server:
      default: http://localhost
      description: The server where the API is hosted.
    port:
      default: config:restApiPort
      description: The port on which the API is running.
paths:
  /login:
    get:
      tags: ['Login']
      responses:
        200:
          description: Successful response. Contains list of roles.
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'                        
        500:
          $ref: '#/components/responses/InternalServerError'
  /cb:
    get:
        tags: ['Login']
        responses:
          200:
            description: Successful response. Contains list of roles.
          400:
            $ref: '#/components/responses/BadRequest'
          401:
            $ref: '#/components/responses/Unauthorized'                        
          500:
            $ref: '#/components/responses/InternalServerError'